"""empty message

Revision ID: 75ff8414c615
Revises: fb2b76a8faf9
Create Date: 2019-05-03 17:40:22.347142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75ff8414c615'
down_revision = 'fb2b76a8faf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entry', sa.Column('server_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'journal_entry', 'server', ['server_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'journal_entry', type_='foreignkey')
    op.drop_column('journal_entry', 'server_id')
    # ### end Alembic commands ###
